[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
# reduce_output = true

# Private

[tasks.desktop_watch]
private = true
watch = { watch = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../src/" ] }

# Public

[tasks.desktop_build]
description = "Build desktop target."
private = false
# extend = "desktop_watch"
category = "Desktop"
command = "cargo"
args = [ "build", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

[tasks.desktop_run]
description = "Run desktop target"
private = false
# extend = "desktop_watch"
category = "Desktop"
command = "cargo"
args = [ "run", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

[tasks.desktop_run_watching]
description = "Run desktop target. Rebuilds app on change"
private = false
extend = "desktop_watch"
category = "Desktop"
command = "cargo"
args = [ "run", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

# [tasks.echo]
# private = false
# command = "echo"
# args = [ "CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY : ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}" ]
