[config] 
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
# reduce_output = true

#### Private

[tasks.watch-desktop]
private = true
watch = { watch = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/src/" ] }

#### Public

[tasks.build]
description = "Build desktop target. Rebuilds on change."
private = false
extend = "watch-desktop"
category = "Build"
command = "cargo"
args = [ "build", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/Cargo.toml" ]

[tasks.run]
description = "Run desktop target. Rebuilds app on change"
private = false
extend = "watch-desktop"
category = "Run"
command = "cargo"
args = [ "run", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/Cargo.toml" ]