[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
# reduce_output = true

# Private

[tasks.desktop_watch]
private = true
watch = { watch = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../src/" ] }

[tasks.desktop_build_release]
description = "Build desktop target for current OS."
private = true
category = "Build"
command = "cargo"
args = [ "build", "--release", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

[tasks.prepare_linux_target_on_mac]
private = true
script_runner = "@shell"
script = '''
rustup target add x86_64-unknown-linux-gnu
brew tap SergioBenitez/osxct
brew install x86_64-unknown-linux-gnu
rm -rf .cargo
mkdir .cargo
echo '[target.x86_64-unknown-linux-gnu]' >> .cargo/config
echo 'linker = "x86_64-unknown-linux-gnu-gcc"' >> .cargo/config
'''

[tasks.desktop_build_linux]
description = "Build desktop target for GNU/Linux distributives."
private = true
category = "Build"
dependencies = [ "prepare_linux_target_on_mac" ]
command = "cargo"
args = [ "build", "--release", "--target", "x86_64-unknown-linux-gnu", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

[tasks.prepare_windows_target_on_mac]
private = true
script_runner = "@shell"
script = '''
brew install mingw-w64
rm -rf .cargo
mkdir .cargo
echo '[target.x86_64-pc-windows-gnu]' >> .cargo/config
echo 'linker = "x86_64-w64-mingw32-gcc"' >> .cargo/config
rustup target add x86_64-pc-windows-gnu
'''

[tasks.desktop_build_windows]
description = "Build desktop target for Windows."
private = true
category = "Build"
dependencies = [ "prepare_windows_target_on_mac" ]
command = "cargo"
args = [ "build", "--release", "--target", "x86_64-pc-windows-gnu", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

# Public

[tasks.desktop_build]
description = "Build desktop target."
private = false
# extend = "desktop_watch"
category = "Desktop"
command = "cargo"
args = [ "build", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

[tasks.desktop_run]
description = "Run desktop target"
private = false
# extend = "desktop_watch"
category = "Desktop"
command = "cargo"
args = [ "run", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

[tasks.desktop_run_watching]
description = "Run desktop target. Rebuilds app on change"
private = false
extend = "desktop_watch"
category = "Desktop"
command = "cargo"
args = [ "run", "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml" ]

# [tasks.echo]
# private = false
# command = "echo"
# args = [ "CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY : ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}" ]
