[placeholders.template_name]
type = "string"
prompt = "What template to use?"
choices = [ "wgpu", "bevy" ]
default = "wgpu"

[placeholders.repository_owner]
type = "string"
prompt = "What is your GitHub username? (This information is required to generate GitHub workflows.)"

[template]
ignore = [
  "module/renderer/.gitignore",
  "module/renderer/step",
  "module/renderer/Makefile.dev.toml",
  "Readme.md.template",
  "module/renderer/Readme.md.template"
]

[conditional.'template_name == "wgpu"']
ignore = [ "module/renderer/bevy" ]

[conditional.'template_name == "bevy"']
ignore = [
  "module/renderer/wgpu",
  "module/renderer/platform/android",
  "module/renderer/platform/ios",
  "module/renderer/platform/wasi",
  "doc/platform/Android.md",
  "doc/platform/iOS.md",
  "private.toml.template",
  "graph.png"
]

[hooks]
pre = [ "post-script.rhai" ]