[workspace]
resolver = "2"
members = [
  "module/renderer",
  "module/renderer/platform/desktop",
  "module/renderer/platform/web",
  "module/renderer/platform/android",
  "module/renderer/platform/ios",
]
exclude = [
  "*",
]
default-members = [ "module/renderer" ]
