[placeholders.template_name]
type = "string"
prompt = "What template to use?"
choices = ["wgpu", "bevy"]
default = "wgpu"

[conditional.'template_name == "wgpu"']
ignore = [ "module/renderer/bevy" ]

[conditional.'template_name == "bevy"']
ignore = [ "module/renderer/wgpu" ]

[hooks]
pre = ["post-script.rhai"]