extend = [
  
  { path = "./desktop/Makefile.toml" },
  { path = "./web/Makefile.toml" }
]

[config] 
skip_core_tasks = true #to skip default predefined flow
# skip_git_env_info = true #??
# skip_rust_env_info = true #??
# skip_crate_env_info = true #??

#### Private

[tasks.watch]
private = true
watch = { watch = [ "./src/" ] }

[tasks.build-android-target]
private = true
command = "cargo"
args = [ "apk", "build" ]

[tasks.run-android-target]
private = true
command = "cargo"
args = [ "apk", "run" ]

[tasks.generate-ios-config]
private = true
condition = { files_not_exist = [ "${CARGO_MAKE_WORKING_DIRECTORY}/ios/project.yml" ] }
# install_crate = "rust-script"
command = "rust-script"
args = [ "${CARGO_MAKE_WORKING_DIRECTORY}/scripts/generate-ios-config.rs" ]

[tasks.generate-ios-project]
# private = true
dependencies = [ "generate-ios-config" ]
condition = { files_not_exist = [ "${CARGO_MAKE_WORKING_DIRECTORY}/ios/webgpu.xcodeproj" ] }
command = "xcodegen"
args = [ "--spec", "ios/project.yml" ]

[tasks.build-ios-target]
private = true
script_runner = "@shell"
script = '''
xcrun xcodebuild -project ios/webgpu.xcodeproj -scheme webgpu_iOS -arch x86_64 -derivedDataPath ios/out
'''

[tasks.run-ios-target]
private = true
script_runner = "@shell"
script = '''
open -a simulator
sleep 5
xcrun simctl install booted ios/out/Build/Products/debug-iphonesimulator/webgpu.app
xcrun simctl launch booted com.example.webgpu
'''

#### Public

[tasks.build-android]
description = "Build android target. Rebuilds on change."
private = false
extend = "watch"
category = "Build"
dependencies = [ "build-android-target" ]

[tasks.run-android]
description = "Run android target. Rebuilds on change."
private = false
extend = "watch"
category = "Run"
dependencies = [ "run-android-target" ]

[tasks.run-ios]
description = "Run ios target. Rebuilds on change."
private = false
category = "Run"
dependencies = [ "generate-ios-project", "build-ios-target", "run-ios-target" ]