extend = [
  
  { path = "./desktop/Makefile.toml" },
  { path = "./web/Makefile.toml" },
  { path = "./ios/Makefile.toml" },
  { path = "./android/Makefile.toml" }
]

[config] 
skip_core_tasks = true #to skip default predefined flow
# skip_git_env_info = true #??
# skip_rust_env_info = true #??
# skip_crate_env_info = true #??
