[config] 
skip_core_tasks = true #to skip default predefined flow

#### Private

[tasks.watch-android]
private = true
watch = { watch = [ "./src/" ] }

[tasks.build-android-target]
private = true
command = "cargo"
args = [ "apk", "build" ]

[tasks.run-android-target]
private = true
command = "cargo"
args = [ "apk", "run" ]

#### Public

[tasks.build-android]
description = "Build android target. Rebuilds on change."
private = false
extend = "watch"
category = "Build"
dependencies = [ "build-android-target" ]

[tasks.run-android]
description = "Run android target. Rebuilds on change."
private = false
extend = "watch"
category = "Run"
dependencies = [ "run-android-target" ]