[package]
name = "game_template_ios"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib", "cdylib"]
path = "src/lib.rs"

[dependencies]
game_template = { path = "../.." }
mobile-entry-point = "0.1.0"
