[package]
name = "webgpu-ios"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib", "cdylib"]
path = "src/lib.rs"

[dependencies]
webgpu = { path = "../.." }
mobile-entry-point = "0.1.0"
