[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true


[env]
IOS_TARGET_NAME = "game_template"

# Private

[tasks.watch_ios]
private = true
watch = { watch = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../src" ] }

[tasks.install_rust_script]
private = true
condition = { files_not_exist = [ "${HOME}/.cargo/bin/rust-script" ] }
script_runner = "@duckscript" # qqq: update to latest after https://github.com/fornwall/rust-script/issues/42
script = '''
exec cargo install rust-script --version "0.7.0"
'''

[tasks.generate_ios_config]
private = true
# condition = { files_not_exist = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml" ] }
dependencies = [ "install_rust_script" ]
command = "rust-script"
args = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/step/generate_ios_config.rs" ]

[tasks.generate_ios_project]
private = true
dependencies = [ "generate_ios_config" ]
# condition = { files_not_exist = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/${IOS_TARGET_NAME}.xcodeproj" ] }
command = "xcodegen"
args = [ "--spec", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml" ]

[tasks.install_cargo_mobile]
private = true
condition = { files_not_exist = [ "${HOME}/.cargo/bin/cargo-mobile" ] }
script_runner = "@duckscript"
script = '''
exec cargo install --git https://github.com/volodymyrmigdal/cargo-mobile.git
'''

[tasks.build_ios_target]
private = true
dependencies = [ "install_cargo_mobile" ]
script_runner = "@duckscript"
script = '''
exec rustup target add x86_64-apple-ios
exec cargo build --manifest-path ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml --target=x86_64-apple-ios
exec xcrun xcodebuild -project ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/${IOS_TARGET_NAME}.xcodeproj -scheme ${IOS_TARGET_NAME}_iOS -arch x86_64 -derivedDataPath ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out
'''

[tasks.build_ios_target_release]
private = true
dependencies = [ "install_cargo_mobile" ]
script_runner = "@duckscript"
script = '''
exec rustup target add x86_64-apple-ios
exec cargo build --manifest-path ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml --target=x86_64-apple-ios --release
exec xcrun xcodebuild -project ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/${GAME_TEMPLATE_IOS_TARGET_NAME}.xcodeproj -scheme ${GAME_TEMPLATE_IOS_TARGET_NAME}_iOS -arch x86_64 -derivedDataPath ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out -configuration release
'''

[tasks.run_ios_target]
private = true
script_runner = "@duckscript"
script = '''
exec open -a simulator
exec sleep 5
exec xcrun simctl install booted ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out/Build/Products/debug-iphonesimulator/${IOS_TARGET_NAME}.app
exec xcrun simctl launch booted com.example.${IOS_TARGET_NAME}
'''

# Public


[tasks.ios_build]
description = "Build debug of ios target."
private = false
category = "iOS"
dependencies = [ "generate_ios_project", "build_ios_target" ]

[tasks.ios_build_release]
description = "Build release of ios target."
private = false
category = "iOS"
dependencies = [ "generate_ios_project", "build_ios_target_release" ]

[tasks.ios_rebuild]
description = "Rebuild debug of ios target."
private = false
category = "iOS"
dependencies = [ "build_ios_target" ]

[tasks.ios_run]
description = "Run debug of ios target."
private = false
category = "iOS"
dependencies = [ "generate_ios_project", "build_ios_target", "run_ios_target" ]

[tasks.ios_run_watching]
description = "Rerun debug of ios target on file change."
private = false
category = "iOS"
extend = "watch_ios"
dependencies = [ "generate_ios_project", "build_ios_target", "run_ios_target" ]

[tasks.ios_clean]
description = "Cleanup generated files of ios target."
category = "iOS"
script_runner = "@duckscript"
script = '''
rm ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../mobile.toml
rm ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml
rm -r ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out
rm -r ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/${IOS_TARGET_NAME}_iOS
rm -r ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/${IOS_TARGET_NAME}.xcodeproj
'''
