[config] 
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

# Private

[tasks.watch-ios]
private = true
watch = { watch = [ "./src/" ] }

[tasks.install_rust_script]
private = true
condition = { files_not_exist = [ "${HOME}/.cargo/bin/rust-script" ] }
script_runner = "@shell"
script = '''
cargo install rust-script
'''

[tasks.generate-ios-config]
private = true
condition = { files_not_exist = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml" ] }
dependencies = [ "install_rust_script" ]
command = "rust-script"
args = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/step/generate_ios_config.rs" ]

[tasks.generate-ios-project]
private = true
dependencies = [ "generate-ios-config" ]
condition = { files_not_exist = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/game_template_ios.xcodeproj" ] }
command = "xcodegen"
args = [ "--spec", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml" ]

[tasks.install_cargo_mobile]
private = true
condition = { files_not_exist = [ "${HOME}/.cargo/bin/cargo-mobile" ] }
script_runner = "@shell"
script = '''
cargo install --git https://github.com/volodymyrmigdal/cargo-mobile.git
'''

[tasks.build-ios-target]
private = true
dependencies = [ "install_cargo_mobile" ]
script_runner = "@shell"
script = '''
rustup target add x86_64-apple-ios
cargo build --manifest-path ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/Cargo.toml --target=x86_64-apple-ios
xcrun xcodebuild -project ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/game_template_ios.xcodeproj -scheme game_template_ios_iOS -arch x86_64 -derivedDataPath ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out
'''

[tasks.run-ios-target]
private = true
script_runner = "@shell"
script = '''
open -a simulator
sleep 5
xcrun simctl install booted ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out/Build/Products/debug-iphonesimulator/game_template_ios.app
xcrun simctl launch booted com.example.game_template_ios
'''

# Public


[tasks.build_ios]
description = "Build ios target."
private = false
category = "iOS"
dependencies = [ "generate-ios-project", "build-ios-target" ]

[tasks.run-ios]
description = "Run ios target. Rebuilds on change."
private = false
category = "iOS"
dependencies = [ "generate-ios-project", "build-ios-target", "run-ios-target" ]

[tasks.clean-ios]
description = "Cleanup generated files of ios target."
category = "iOS"
script_runner = "@duckscript"
script = '''
rm ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/mobile.toml
rm ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml
rm -r ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out
rm -r ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/game_template_ios_iOS
rm -r ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/game_template_ios.xcodeproj
'''
