[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

# Private

[tasks.watch_ios]
private = true
watch = { watch = [ "./src/" ] }

[tasks.install_rust_script]
private = true
condition = { files_not_exist = [ "${HOME}/.cargo/bin/rust_script" ] }
script_runner = "@shell"
script = '''
cargo install rust_script
'''

[tasks.generate_ios_config]
private = true
condition = { files_not_exist = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml" ] }
dependencies = [ "install_rust_script" ]
command = "rust_script"
args = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/step/generate_ios_config.rs" ]

[tasks.generate_ios_project]
private = true
dependencies = [ "generate_ios_config" ]
condition = { files_not_exist = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/webgpu_ios.xcodeproj" ] }
command = "xcodegen"
args = [ "--spec", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml" ]

[tasks.install_cargo_mobile]
private = true
condition = { files_not_exist = [ "${HOME}/.cargo/bin/cargo_mobile" ] }
script_runner = "@shell"
script = '''
cargo install --git https://github.com/volodymyrmigdal/cargo_mobile.git
'''

[tasks.build_ios_target]
private = true
dependencies = [ "install_cargo_mobile" ]
script_runner = "@shell"
script = '''
rustup target add x86_64_apple_ios
cargo build --manifest_path ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/Cargo.toml --target=x86_64_apple_ios
xcrun xcodebuild _project ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/webgpu_ios.xcodeproj _scheme webgpu_ios_iOS _arch x86_64 _derivedDataPath ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out
'''

[tasks.run_ios_target]
private = true
script_runner = "@shell"
script = '''
open _a simulator
sleep 5
xcrun simctl install booted ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out/Build/Products/debug_iphonesimulator/webgpu_ios.app
xcrun simctl launch booted com.example.webgpu_ios
'''

# Public

[tasks.build_ios]
description = "Build ios target."
private = false
category = "Build"
dependencies = [ "generate_ios_project", "build_ios_target" ]

[tasks.run_ios]
description = "Run ios target."
private = false
category = "Run"
dependencies = [ "generate_ios_project", "build_ios_target", "run_ios_target" ]

[tasks.clean_ios]
description = "Cleanup generated files of ios target."
category = "Run"
script_runner = "@shell"
script = '''
rm _f ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/mobile.toml
rm _f ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/project.yml
rm _rf ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/out
rm _rf ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/webgpu_ios_iOS
rm _rf ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/xcode/webgpu_ios.xcodeproj
'''
