[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[env]
CARGO_MAKE_WEB_PORT = 8080 # qqq : !

# Private

[tasks.web_watch]
private = true
watch = { postpone = true, watch = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../src/" ] }

[tasks.web_install_wasm]
private = true
install_script = "rustup target add wasm32-unknown-unknown"

[tasks.web_build_target_debug]
private = true
command = "cargo"
args = [
  "build",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "web",
  "--target", "wasm32-unknown-unknown",
  "--features", "web",
]

[tasks.web_build_target_release]
private = true
install_script = "rustup target add wasm32-unknown-unknown"
command = "cargo"
args = [
  "+nightly",
  "build",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "web",
  "--target", "wasm32-unknown-unknown",
  "--features", "web",
  "--profile", "release_web",
  "-Z", "build-std=std,panic_abort", # rebuild std
  "-Z", "build-std-features=panic_immediate_abort", # rebuild std with abort, without unwind
]

[tasks.web_wasm_rebuild_debug]
private = true
command = "wasm-bindgen"
args = [
  "--target", "web",
  # "--browser" #qqq: ???
  "--out-dir", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/web",
  "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/wasm32-unknown-unknown/debug/web.wasm",
  "--debug",
  "--keep-debug",
]

[tasks.web_wasm_build_debug]
extend = "web_wasm_rebuild_debug"
install_crate = "wasm-bindgen-cli"

[tasks.web_wasm_build_release]
private = true
install_crate = "wasm-bindgen-cli"
command = "wasm-bindgen"
args = [
  "--target", "web",
  "--out-dir", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/web",
  "--remove-name-section",
  "--remove-producers-section",
  "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/wasm32-unknown-unknown/release_web/web.wasm",
]

[tasks.web_build_copy_static] # qqq : hardlink files?
private = true
script_runner = "@duckscript"
script = '''
glob_cp ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/static/* ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/web
'''

[tasks.web_wasm_optimize]
private = true
# install_crate = "?" # qqq : find crate installing wasm-opt
command = "wasm-opt"
args = [
  "-Oz",
  "-o", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/web/web_bg.wasm",
  "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/web/web_bg.wasm",
  "--strip-debug",
  "--simplify-globals",
  "--vacuum",
]

# wasm-opt -Oz -o target/web/web_bg.wasm target/web/web_bg.wasm

[tasks.web_install_npm_dependencies] # qqq : ? aaa:done
description = "Install npm dependencies for web target."
private = true
category = "Prerequisites"
script_runner = "@shell"
script = '''
cd ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}
npm i
'''

[tasks.web_server_browsersync]
private = true
dependencies = [ "web_install_npm_dependencies" ]
command = 'node'
args = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/step/BrowserSync.ss" ]

# Public

[tasks.web_server_run]
private = false
install_crate = "basic-http-server"
command = "basic-http-server"
args = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../target/web", "-a", "127.0.0.1:${CARGO_MAKE_WEB_PORT}" ]

[tasks.web_build]
description = "Build debug of web target." # qqq : ?? aaa:done
private = false
category = "Web"
dependencies = [ "web_install_wasm", "web_build_target_debug", "web_wasm_build_debug", "web_build_copy_static" ]

[tasks.web_build_release]
description = "Build release of web target."
private = false
category = "Web"
dependencies = [ "web_install_wasm", "web_build_target_release", "web_wasm_build_release", "web_build_copy_static", "web_wasm_optimize" ]
# dependencies = [ "web_install_wasm", "web_build_target_release", "web_wasm_build_release", "web_build_copy_static" ]

[tasks.web_rebuild]
description = "Rebuild debug of web target." # qqq : ?? aaa:done
private = false
category = "Web"
dependencies = [ "web_build_target_debug", "web_wasm_rebuild_debug", "web_build_copy_static" ]
# qqq : why no web_build_copy_static?? aaa:added

[tasks.web_rebuild_watching]
description = "Rebuild debug of web target on file change."
private = false
category = "Web"
extend = "web_watch"
dependencies = [ "web_rebuild" ]

[tasks.web_run]
description = "Build and run web target."
category = "Web"
run_task = { name = [ "web_build", "web_server_run" ] }

[tasks.web_rerun]
description = "Rebuild debug of web target and run it."
category = "Web"
run_task = { name = [ "web_rebuild", "web_server_run" ] }

[tasks.web_rerun_watching] # qqq : ??? aaa:done
description = "Rebuild and reload debug of web target on file change."
category = "Web"
run_task = { name = [ "web_rebuild_watching", "web_server_browsersync" ], parallel = true }

# qqq : watching builds? aaa:done
# qqq : release builds?
# qqq : add to prerequisities wasm-opt

# [tasks.echo]
# command = "echo"
# args = [ "CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY : ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}" ]

#
# # 20 the largest functions
# twiggy top -n 20 target/web/web_bg.wasm
#
# # Optimize for size.
# wasm-opt -Os -o target/web/web_bg.wasm target/web/web_bg.wasm
#
# # Optimize aggressively for size.
# wasm-opt -Oz -o target/web/web_bg.wasm target/web/web_bg.wasm
#
# # Optimize for speed.
# wasm-opt -O -o target/web/web_bg.wasm target/web/web_bg.wasm
#
# # Optimize aggressively for speed.
# wasm-opt -O3 -o target/web/web_bg.wasm target/web/web_bg.wasm
#
# # remove a function
# wasm-snip target/web/web_bg.wasm -o target/web/web_bg.wasm function1
#
# # for object bin files
# nm -S -td --size-sort target/x86_64-unknown-linux-gnu/release/x|rustfilt|tac|cut -d' ' -f 2-|less
#