[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

# Private

[tasks.watch_android]
private = true
watch = { watch = [ "./src/" ] }

[tasks.build_android_target]
private = true
command = "cargo"
args = [ "apk", "build", "--manifest_path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/Cargo.toml" ]

[tasks.run_android_target]
private = true
command = "cargo"
args = [ "apk", "run", "--manifest_path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/Cargo.toml" ]

# Public

[tasks.build_android]
description = "Build android target. Rebuilds on change."
private = false
extend = "watch_android"
category = "Build"
dependencies = [ "build_android_target" ]

[tasks.run_android]
description = "Run android target. Rebuilds on change."
private = false
extend = "watch_android"
category = "Run"
dependencies = [ "run_android_target" ]