[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

# Private

[tasks.watch_android]
private = true
watch = { postpone = true, watch = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../src/" ] }

[tasks.build_android_target_debug]
private = true
command = "cargo"
args = [
  "apk",
  "build",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml"
]

[tasks.build_android_target_release]
private = true
command = "cargo"
args = [
  "apk",
  "build",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--release"
]

[tasks.run_android_target]
private = true
command = "cargo"
args = [
  "apk",
  "run",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml"
]

# Public

[tasks.android_build]
description = "Build debug of android target."
private = false
category = "Android"
dependencies = [ "build_android_target_debug" ]

[tasks.android_build_release]
description = "Build release of android target."
private = false
category = "Android"
dependencies = [ "build_android_target_release" ]

[tasks.android_rebuild]
description = "Rebuild debug of android target."
private = false
category = "Android"
dependencies = [ "build_android_target_debug" ]

[tasks.android_run]
description = "Run android target."
private = false
category = "Android"
dependencies = [ "run_android_target" ]

[tasks.android_run_watching]
description = "Rebuild and reaload android target on file change."
private = false
category = "Android"
extend = "watch_android"
dependencies = [ "run_android" ]