[package]
name = "game_template"
version = "0.0.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/game_template"
repository = "https://github.com/Wandalen/rust_game_template/"
homepage = "https://github.com/Wandalen/rust_game_template/"
description = """
Neutral cross-platform Rust game template.
"""
categories = [ "game-development", "game-engines" ]
keywords = [ "game-template", "gamedev" ]

include = [
  "/src",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
webgl = [ "wgpu/webgl" ]
web-sys = [ "winit/web-sys" ]
default = [ "webgl", "web-sys" ]

# [lib]
# name = "game_template"
# path = "./src/main.rs"

[dependencies]
wgpu = "0.11.0"
winit = "0.25.0"
pollster = "0.2"
byte-slice-cast = "1.2.0"
bytemuck = { version = "1.7.2", features = [ "derive" ] }

