extend = [

  { path = "./platform/desktop/Makefile.toml" },
  { path = "./platform/web/Makefile.toml" },
  # {% if template_name == "wgpu" %}
  { path = "./platform/ios/Makefile.toml" },
  { path = "./platform/android/Makefile.toml" },
  { path = "./platform/wasi/Makefile.toml" }
  # {% endif %}

]

[config]
skip_core_tasks = true # to skip default predefined flow
# skip_git_env_info = true #??
# skip_rust_env_info = true #??
# skip_crate_env_info = true #??

[tasks.init]
script_runner = "@duckscript"
condition = { env_set = [ "GAME_TEMPLATE" ] }
script = '''
glob_cp ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/${GAME_TEMPLATE}/src/* ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/src
cp ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/${GAME_TEMPLATE}/Cargo.toml ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/Cargo.toml
'''

[tasks.default]
extend = "desktop_run"

[tasks.test]
category = "General"
description = "Run tests"
command = "cargo"
args = [ "test" ]

[tasks.doc_dep_graph]
category = "General"
description = "Generate dependancy graph."
private = false
script_runner = "@shell"
script = '''
cargo depgraph --all-deps --dedup-transitive-deps |
  dot -Tjpg > ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../doc/dep_graph.jpg
'''


[tasks.doc_ref]
category = "General"
description = "Generate reference"
command = "cargo"
args = [
  "doc",
  "--target-dir", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../target/reference",
]

[tasks.doc]
category = "General"
description = "Generate full documentation"
run_task = { name = [ "doc_dep_graph", "doc_ref" ], parallel = true }
# dependencies = [ "doc_dep_graph", "doc_ref" ]
