extend = [
  { path = "./platform/desktop/Makefile.toml" },
  { path = "./platform/web/Makefile.toml" },
  { path = "./platform/ios/Makefile.toml" },
  { path = "./platform/android/Makefile.toml" },
  { path = "./platform/wasi/Makefile.toml" }
]

[config]
skip_core_tasks = true #to skip default predefined flow
# skip_git_env_info = true #??
# skip_rust_env_info = true #??
# skip_crate_env_info = true #??

[tasks.default]
extend = "desktop_run"

[tasks.test]
category = "General"
description = "Run tests"
command = "cargo"
args = [ "test" ]

# [tasks.doc_dep_graph]
# description = "Generate dependancy graph."
# private = true
# script_runner = "@duckscript"
# script = '''
# cargo depgraph --all-deps --dedup-transitive-deps | dot -Tpng > ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../../../doc/dep_graph.png
# '''

[tasks.doc]
category = "General"
description = "Generate documentation"
command = "cargo"
args = [
  "doc",
  "--target-dir", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../target/reference",
]
