name: AndroidCommon

on: [ workflow_call ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo-mobile/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: davidB/rust-cargo-make@v1
      - name: Build project
        run: |
              unset ANDROID_HOME
              rustup target add aarch64-linux-android
              cargo make android_build


