
name: AndroidPush

on :
  push :
    branches : [ alpha ]

jobs:
  build:
    if: "contains( github.event.head_commit.message, '[build]' )"
    uses: ${{ github.repository }}/.github/workflows/AndroidCommon.yml@master

