name: AndroidCommon

on:
  workflow_call:
    inputs:
      artifacts:
        required: true
        type: string
      toolchain:
        required: true
        type: string
      build:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ inputs.toolchain }}
            override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo-mobile/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: davidB/rust-cargo-make@v1
      - run: unset ANDROID_HOME
      - run: rustup target add aarch64-linux-android
      - name: Build
        if: ${{ inputs.build == 'fast' }}
        run: cargo make android_build
      - name: Build
        if: ${{ inputs.build != 'fast' }}
        run: cargo make android_build_release
      - name: Upload
        if: ${{ inputs.artifacts == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: target/release/apk
          retention-days: 1

