
name: AndroidPush

on :
  push :
    branches : [ alpha ]

jobs:
  build:
    if: "contains( github.event.head_commit.message, '[build]' )"
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/AndroidCommon.yml@master

