
name : BetaPrApprove

on:
  pull_request_target:
    types: [ opened, reopened, edited ]

jobs :

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        with:
          target: beta
          exclude: Wandalen:alpha
          change-to: alpha
          comment: |
            To save the application stability the repository uses a system to forward changes from an unstable branch to a stable.
            The unstable branch is `alpha`. All user pull requests should be opened to this branch.
            The staging branch is `beta`. Changes to this branch are forwarded by a pull request from branch `alpha` automatically.
            The stable branch is `master`. Changes to this branch are forwarded by a pull request from branch `beta` automatically. Forwarded changes merge manually after review.

            The base branch of this PR has been automatically changed to `alpha` taking into account the described system `alpha -> beta -> master`.
            Please, check that there are no merge conflicts.
