name: alpha

on:
  push:
    branches: [ 'beta' ]

jobs:
  build:
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - uses: davidB/rust-cargo-make@v1

      - name: Build project for MacOS
        run: cargo make desktop_build_release

      - name: Build project for GNU/Linux
        run: cargo make desktop_build_linux

      - name: Build project for Windows
        run: cargo make desktop_build_windows

      - uses: actions/upload-artifact@v2
        with:
          name: targets
          path: |
            target/release/game_template
            target/x86_64-unknown-linux-gnu/release/game_template
            target/x86_64-pc-windows-gnu/release/game_template.exe
            target/x86_64-pc-windows-gnu/release/game_template.dll

  merge :
    if : |
      startsWith( github.event.head_commit.message, 'version' ) && startsWith( github.ref, 'refs/tags/v' )
      || startsWith( github.event.head_commit.message, '[Automated]' )
    needs : build
    runs-on : macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.PRIVATE_TOKEN }}
          source_ref: beta
          target_branch: gamma
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
