name: Desktop

on:
  # push:
  #   branches: [ 'alpha' ]
  pull_request:
    branches: [ 'alpha' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    if: ${{ contains(github.event.head_commit.message, '[build]') }}

    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

