
name : Forward

on :
  push :
    branches : [ alpha ]

jobs :

  android:
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/AndroidPush.yml@alpha
  desktop:
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/DesktopPush.yml@alpha
  ios:
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/IosPush.yml@alpha
  web:
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/WebPush.yml@alpha

  merge :
    needs: [ android, desktop, ios, web ]
    runs-on : ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1
      - uses : everlytic/branch-merge@1.1.2
        with :
          github_token : ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          source_ref : alpha
          target_branch : beta
          commit_message_template : 'Merged {source_ref} into target {target_branch} [Automated]'

