name: iOS

on:
  # push:
  #   branches: [ 'alpha' ]
  pull_request:
    branches: [ 'alpha' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    if: ${{ contains(github.event.head_commit.message, '[ios]') }}

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo-mobile/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            module/renderer/target/
            module/renderer/platform/*/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: davidB/rust-cargo-make@v1
      - name: Install dependencies
        run: |
          brew install ios-deploy
          brew install xcodegen
      - name: Create private config file
        env:
           PRIVATE_TOML: ${{ secrets.PRIVATE_CONFIG }}
        run: 'echo "$PRIVATE_TOML" > private.toml'
        shell: bash
      - name: Build project
        run: cargo make build_ios


