
name: IosPush

on :
  push :
    branches : [ alpha ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "contains( github.event.head_commit.message, '!test' )"
    uses: Wandalen/rust_game_template/.github/workflows/IosCommon.yml@alpha
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'stable'

