
name: IosPush

on :
  push :
    branches : [ alpha ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "contains( github.event.head_commit.message, '[build]' )"
    uses: ${{ github.repository }}/.github/workflows/IosCommon.yml@master

