
name: iOSPr

on :
  pull_request:
    branches: [ 'alpha' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on : ubuntu-latest
    steps :
      - name: List commits on the pull request
        run: |
          response=$(curl --request GET \
          --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
          --header 'Authorization: token ${{ secrets.PRIVATE_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Content-Type: application/json')
          echo $response > response.json
      - name: Get latest commit
        id: message
        run: |
          length=$(jq 'length' response.json)
          index=$(($length - 1))
          latest_commit=$(jq --argjson index $index '.[$index]' response.json)
          latest_commit_message=$(echo "$latest_commit" | jq -r '.commit.message')
          echo "::set-output name=message::$latest_commit_message"
      - name : Exit with fail
        if: "${{ !startsWith( steps.message.outputs.message, '[build]' ) }}"
        run: exit 1

  build:
    needs: check
    if: success()
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/iOSCommon.yml@alpha

