
name: Push

on :
  push :
    branches : [ alpha ]

jobs:
  android:
    if: "contains( github.event.head_commit.message, '[build]' )"
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/AndroidCommon.yml@master
  desktop:
    if: "contains( github.event.head_commit.message, '[build]' )"
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/DesktopCommon.yml@master
    with:
      artifacts: 'false'
  ios:
    if: "contains( github.event.head_commit.message, '[build]' )"
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/IosCommon.yml@master
  web:
    if: "contains( github.event.head_commit.message, '[build]' )"
    uses: Learn-Together-Pro/rust_game_template/.github/workflows/WebCommon.yml@master
