
name: Web

on:
  # push:
  #   branches: [ 'alpha' ]
  pull_request:
    branches: [ 'alpha' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ contains(github.event.head_commit.message, '[build]') }}

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: davidB/rust-cargo-make@v1

      - name: Build project for web
        run: cargo make web_build

