name: alpha

on:
  push:
    branches: [ 'alpha' ]

jobs:
  build:
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - uses: davidB/rust-cargo-make@v1

      - name: Build project for web
        run: cargo make web_build

      - uses: actions/upload-artifact@v2
        with:
          name: web_app
          path: target/web
