
name: WebCommon

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      build:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          override: true
      - uses: davidB/rust-cargo-make@v1

      - name: Build
        if: ${{ inputs.build == 'fast' }}
        run: cargo make web_build
      - name: Build
        if: ${{ inputs.build != 'fast' }}
        run: cargo make web_build_three_targets

